// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Behavior } from "./Behavior";

export type ActionStrength = { behavior: Behavior, value: number, };
