// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Periodic sample of the rat's mind, for the history plots.
 */
export type AssocSample = { t: number, soundFood: number, barSound: number, barStrength: number, fear: number, painSensitivity: number, vLight: number, vTone: number, vBell: number, };
