// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Behavior = "walk" | "sniff" | "lookAround" | "rear" | "rearWall" | "groom" | "faceWipe" | "scratch" | "drink" | "eat" | "barPress" | "beg" | "roll" | "freeze" | "startle" | "orient";
