// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsLevel } from "./UsLevel";

export type ChamberView = { pellets: number, leverDown: boolean, lightOn: boolean, toneDb: number | null, bellOn: boolean, shock: UsLevel | null, dispenseCount: number, shockCount: number, };
