// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClassicalProgress = { 
/**
 * Current stage, from 1.
 */
stage: number, stageCount: number, 
/**
 * Current trial within the stage, from 1.
 */
trialInStage: number, trialsInStage: number, totalTrial: number, totalTrials: number, inCs: boolean, 
/**
 * Seconds until the CS comes on (between trials) or goes off (during the CS).
 */
remaining: number, };
