// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassicalDesign } from "./ClassicalDesign";
import type { OperantDesign } from "./OperantDesign";
import type { RatTemplate } from "./RatTemplate";

/**
 * Actions on the simulated experiment.
 */
export type Command = { "type": "givePellet" } | { "type": "markRecord", label: string | null, } | { "type": "setOperantDesign", design: OperantDesign, } | { "type": "setClassicalDesign", design: ClassicalDesign, } | { "type": "startClassical" } | { "type": "stopClassical" } | { "type": "timeOff", hours: number, } | { "type": "newRat", template: RatTemplate, seed: number, } | { "type": "randomizePosition" };
