// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which conditioned stimuli a trial presents.
 */
export type CsSpec = { light: boolean, 
/**
 * Tone intensity in dB, or no tone.
 */
toneDb: number | null, bell: boolean, };
