// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssocSample } from "./AssocSample";
import type { BehaviorStart } from "./BehaviorStart";
import type { RecordEvent } from "./RecordEvent";
import type { TrialRecord } from "./TrialRecord";

/**
 * Data recorded since the previous frame.
 */
export type Delta = { events: Array<RecordEvent>, trials: Array<TrialRecord>, samples: Array<AssocSample>, behaviors: Array<BehaviorStart>, };
