// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Delta } from "./Delta";
import type { HostStatus } from "./HostStatus";
import type { Snapshot } from "./Snapshot";

export type Frame = { snapshot: Snapshot, host: HostStatus, delta: Delta, };
