// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssocSample } from "./AssocSample";
import type { ClassicalDesign } from "./ClassicalDesign";
import type { HostStatus } from "./HostStatus";
import type { RecordEvent } from "./RecordEvent";
import type { Snapshot } from "./Snapshot";
import type { TrialRecord } from "./TrialRecord";

/**
 * Everything the interface needs to rebuild itself (after opening a file, for instance).
 */
export type FullState = { snapshot: Snapshot, host: HostStatus, events: Array<RecordEvent>, trials: Array<TrialRecord>, samples: Array<AssocSample>, classicalDesign: ClassicalDesign, };
