// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State of the runner that drives the simulation.
 */
export type HostStatus = { paused: boolean, 
/**
 * Program seconds per real second while the rat is visible.
 */
speed: number, isolated: boolean, 
/**
 * Program seconds per real second while the rat is isolated.
 */
isolatedSpeed: number, };
