// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionStrength } from "./ActionStrength";

export type MindView = { soundFood: number, barSound: number, barStrength: number, fear: number, painSensitivity: number, vLight: number, vTone: number, vBell: number, actions: Array<ActionStrength>, };
