// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Reinforcer } from "./Reinforcer";
import type { Schedule } from "./Schedule";

export type OperantDesign = { schedule: Schedule, reinforcer: Reinforcer, };
