// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Starting points for a new rat.
 */
export type RatTemplate = "naive" | "barTrained";
