// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Behavior } from "./Behavior";
import type { Facing } from "./Facing";

export type RatView = { x: number, z: number, facing: Facing, behavior: Behavior, 
/**
 * Seconds since the current bout started.
 */
elapsed: number, duration: number, };
