// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CsSpec } from "./CsSpec";
import type { ReinforcerKind } from "./ReinforcerKind";
import type { UsLevel } from "./UsLevel";

export type RecordEvent = { "type": "press", t: number, reinforced: boolean, } | { "type": "reinforcer", t: number, kind: ReinforcerKind, } | { "type": "mark", t: number, label: string, } | { "type": "csOn", t: number, cs: CsSpec, } | { "type": "csOff", t: number, } | { "type": "shock", t: number, level: UsLevel, } | { "type": "designChange", t: number, label: string, } | { "type": "timeOff", t: number, hours: number, } | { "type": "classicalStart", t: number, } | { "type": "classicalEnd", t: number, completed: boolean, };
