// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Schedule = { "kind": "continuous" } | { "kind": "fixedRatio", n: number, } | { "kind": "variableRatio", n: number, } | { "kind": "fixedInterval", seconds: number, } | { "kind": "variableInterval", seconds: number, };
