// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Frame } from "./Frame";
import type { FullState } from "./FullState";

export type SimMessage = { "type": "frame", "data": Frame } | { "type": "reset", "data": FullState };
