// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChamberView } from "./ChamberView";
import type { ClassicalProgress } from "./ClassicalProgress";
import type { Counters } from "./Counters";
import type { MindView } from "./MindView";
import type { OperantDesign } from "./OperantDesign";
import type { RatView } from "./RatView";

export type Snapshot = { 
/**
 * Program time in seconds.
 */
t: number, rat: RatView, chamber: ChamberView, mind: MindView, counters: Counters, operant: OperantDesign, classical: ClassicalProgress | null, };
