// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrialType } from "./TrialType";

export type Stage = { trialTypes: Array<TrialType>, 
/**
 * Mean interval between trials, in minutes. Each interval varies by ±50%.
 */
meanItiMinutes: number, };
