// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CsSpec } from "./CsSpec";
import type { UsLevel } from "./UsLevel";

/**
 * Results of one classical conditioning trial.
 */
export type TrialRecord = { 
/**
 * Trial number in the whole experiment, from 1.
 */
trial: number, 
/**
 * Stage number, from 1.
 */
stage: number, trialInStage: number, 
/**
 * Time of CS onset.
 */
t: number, cs: CsSpec, us: UsLevel, prePresses: number, csPresses: number, suppressionRatio: number | null, 
/**
 * Seconds spent moving in the 30 s before the CS.
 */
preMove: number, 
/**
 * Seconds spent moving during the CS.
 */
csMove: number, movementRatio: number | null, 
/**
 * CS response strengths after the trial.
 */
vLight: number, vTone: number, vBell: number, fearPeak: number, painSensitivity: number, };
