// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CsSpec } from "./CsSpec";
import type { UsLevel } from "./UsLevel";

export type TrialType = { cs: CsSpec, us: UsLevel, count: number, };
